Some renaming
itchysats/10101 pull request #140
Opened 2022-11-08 04:07 UTC by da-kami

Rename a few things in preparation for #139 - better get this in early so we don't run into friction working in parallel :)

2022-11-08 04:10 UTC, klochowicz reviewed
I'm not sure whether Dashboard should be the same as the whole LightningWallet screen.
I think having the ability to *not* see trading prompts for when I'm looking through my transaction history would be cool.
In other words, I'm not too keen on `Dashboard` rename.

2022-11-08 04:21 UTC, da-kami commented
> I'm not sure whether Dashboard should be the same as the whole LightningWallet screen. I think having the ability to _not_ see trading prompts for when I'm looking through my transaction history would be cool. In other words, I'm not too keen on `Dashboard` rename.

I think if we want a `Dashboard` it should be on a different level. For me `Dashboard` is an abstract word that does not add any benefit in the current context. We have a wallet view, and we are in a wallet context.

I can imagine that in the future we might have another hierarchy level on top where one can see all kind of activities of what happened - that could be a `Dashboard` then, but I don't think that's what we currently have. I think `Wallet` makes more sense in what was implemented so far - and even more with the changes outlined by #139 and #113

2022-11-08 04:24 UTC, da-kami commented
Note: For implementing #139 I will have to rename `Dashboard` to be in a lightning wallet context because there will be another view that is the Bitcoin wallet. I might be able to keep the `Dashboard` terminology as widget on top, but I don't think this makes sense in the current modularization. 

In the future we can hopefully get rid of needing a Bitcoin hot-wallet in the application, but for now we need it. cc @bonomat

2022-11-08 04:30 UTC, klochowicz commented
maybe I'll rephrase: the current widget, with big buttons about trading, is not perfect for the "wallet view" IMHO. this might be subjective, so if others I happy with the rename, I will not stop you :-)

2022-11-08 04:31 UTC, holzeis requested changes
I suggest we finish this https://github.com/itchysats/10101/discussions/122 discussion, before we renaming / restructuring things.

2022-11-08 05:09 UTC, da-kami commented
> maybe I'll rephrase: the current widget, with big buttons about trading, is not perfect for the "wallet view" IMHO. this might be subjective, so if others I happy with the rename, I will not stop you :-)

I agree and recorded this observation in https://github.com/itchysats/10101/discussions/138#discussioncomment-4081307

2022-11-08 05:12 UTC, da-kami commented
> I suggest we finish this #122 discussion, before we renaming / restructuring things.

Note: @holzeis and me had a discussion including wireframe walkthrough and he will have anoher look at the changes. 
I think #122 makes sense, but I would probably see most of that discussion as post-tournament task. I don't expect to extend the POC we build, see #138 :)

2022-11-08 23:51 UTC, da-kami commented
@holzeis should this still be blocked? You re-requested a review from yourself, but it seems no review was done? 😅

2022-11-09 07:35 UTC, holzeis approved these changes
@da-kami feel free to merge to unblock your follow up PR. However, I would like to come back to the project structuring and naming conventions once we have concluded the discussion in #122

2022-11-09 07:35 UTC, holzeis commented on integration_test/dashboard_test.dart
> -          return const Dashboard();
🤔  I guess we should rename the test file as well if its now testing the wallet lightning component instead of the dashboard.

2022-11-09 07:35 UTC, holzeis commented on lib/cfd_trading/cfd_offer.dart
> +import 'package:ten_ten_one/cfd_trading/cfd_trading_change_notifier.dart';
fine with me, but for this kind of change I would have waited for the conclusion of #122.

2022-11-09 23:41 UTC, da-kami commented
Closing in favor of https://github.com/itchysats/10101/pull/146
Sorry for the back and forth, it was not a good idea to try to do these changes separate.

2022-11-09 23:41 UTC, closed without merging