chore: Remove margin from cfd
itchysats/10101 pull request #309
Opened 2022-11-22 14:32 UTC by holzeis

We don't need to store the margin on the cfd as it can be calculated from the other attributes.

2022-11-22 22:29 UTC, bonomat approved these changes
Happy to get this in, but for the record, it is actually the other way around: 
In a perpetual CFD the leverage is calculated from the margin because the margin will increase/decrease over time due to funding rate.

2022-11-22 23:14 UTC, da-kami reviewed
I would not merge this, we had this discussion on itchysats for some time and in the end we regretted not storing the `margin`. I don't think this is needed for the demo :)

2022-11-22 23:15 UTC, da-kami requested changes
We regretted not storing the margin in Itchysats in the end. Yes, it can be calculated - but it is a value that does not change - calculation just makes this cumbersome.

2022-11-22 23:27 UTC, bonomat commented
Closing this for now as it's not planned.

2022-11-22 23:27 UTC, closed without merging

2022-11-23 04:24 UTC, holzeis commented
We should fix how the margin is stored then. Milli sats is unexpected and not consistent with the other properties.