chore: generate bridge code on cargo build
itchysats/10101 pull request #72
Opened 2022-10-27 11:34 UTC by holzeis

Integrates the flutter_rust_bridge_generator into the build.rs.

Eliminates the necessity of running make gen everything you change rust code. code generation is executed with cargo build.

https://cjycode.com/flutter_rust_bridge/feature/build_rs.html

2022-10-27 23:43 UTC, klochowicz reviewed
Interesting stuff! this has potential of making working across FFI boundary  a bit more convenient.

🤔However, I have a few open questions:
- how to deal with cache invalidation issues caused by `build.rs`? we have run into that in the past with other crate, and this slowed down CI builds 
- would this trigger multiple runs of the codegen when we're building for multiple targets at once? (like with `cargo-ldk` or `cargo-lipo`?).

2022-10-27 23:45 UTC, klochowicz commented
also, it seems to fail on the actual Android integration test (and clippy too)

2022-10-27 23:50 UTC, klochowicz requested changes
after looking at CI action results, I don't think this is feasible - making our Rust builds depend on Flutter toolkit does not sound like a good idea.

2022-10-27 23:50 UTC, klochowicz commented on rust/build.rs
> +        frb_codegen(config, &all_symbols).unwrap();
this seems to pull Flutter in after all 🙁
https://github.com/itchysats/10101/actions/runs/3337012818/jobs/5522841154

2022-10-31 04:56 UTC, holzeis commented
closing that PR as running the generation in the build.rs does not seem to properly work.

2022-10-31 04:56 UTC, closed without merging